using System.Collections.Frozen;

namespace OpenTail.Stingray.Core;

/// <summary>
/// Every <c>STINGRAY_*</c> environment variable the engine actually reads.
///
/// <para><b>Why this exists.</b> These variables are read ad hoc with
/// <c>Environment.GetEnvironmentVariable</c> at ~141 sites. A misspelling is therefore
/// indistinguishable from "not set" — dropping the "D" from the KV-dtype variable's name silently
/// does nothing, and the user sees a run that ignored their configuration without saying so.
/// <c>FindUnknown</c> turns that silence into a warning.</para>
///
/// <para>Note the doc comments here deliberately avoid spelling out example misspellings: the
/// drift test scans source text for the literal prefix, so an invented name in a comment would be
/// counted as a usage. (It was — that is how this sentence came to be written.)</para>
///
/// <para><b>Maintenance.</b> Generated by scanning <c>src/**/*.cs</c> for the literal prefix; see
/// <c>docs/env-var-inventory.md</c>. `KnownEnvironmentVariableTests` re-scans the source tree and
/// fails if this list drifts, so adding a new variable without listing it here breaks the build
/// rather than silently widening the surface.</para>
///
/// <para>Membership here means "the engine reads it", NOT "it is supported configuration". Many
/// are diagnostic or benchmark-only switches. Classification lives in the inventory doc.</para>
/// </summary>
public static class KnownEnvironmentVariables
{
    /// <summary>Prefix identifying a setting intended for this engine.</summary>
    public const string Prefix = "STINGRAY_";

    /// <summary>Names read anywhere in the engine. Ordinal comparison — these are case-sensitive on Unix.</summary>
    public static readonly FrozenSet<string> All = new[]
    {
        "STINGRAY_ACT_SOA",
        "STINGRAY_ACT_SOA_CPA",
        "STINGRAY_ATTN_WAVE_BUDGET_MB",
        "STINGRAY_BACKEND",
        "STINGRAY_BATCHED_ATTN",
        "STINGRAY_BATCHED_CPU_FFN",
        "STINGRAY_BATCHED_FFN",
        "STINGRAY_BATCHED_GDN_SCAN",
        "STINGRAY_BATCHED_MATVEC_TIER",
        "STINGRAY_BATCHED_PREFILL",
        "STINGRAY_BATCHED_TRUNK",
        "STINGRAY_BATCH_DECODE_GEMM",
        "STINGRAY_BATCH_DECODE_MMQ",
        "STINGRAY_BATCH_DECODE_RAGGED",
        "STINGRAY_BATCH_DECODE_WS",
        "STINGRAY_BATCH_DECODE_WS_V2",
        "STINGRAY_BYPASS_ATTN",
        "STINGRAY_BYPASS_GDN",
        "STINGRAY_BYPASS_MOE",
        "STINGRAY_CPU_GDN",
        "STINGRAY_CPU_MICRO_GEMM",
        "STINGRAY_Q4K_MICRO_GEMM",
        "STINGRAY_MICRO_GEMM",
        "STINGRAY_CPU_MOE",
        "STINGRAY_CPU_PREFILL_Q8",
        "STINGRAY_CPU_KPACK_SIMD",
        "STINGRAY_CPU_VNNI",
        "STINGRAY_CPU_THREADS",
        "STINGRAY_CUDA13",
        "STINGRAY_CUDA_GRAPH",
        "STINGRAY_CUDA_MATVEC_BENCH",
        "STINGRAY_CUDA_PRECISION",
        "STINGRAY_CUDA_PROFILE",
        "STINGRAY_DECODE_CUDA_GRAPH",
        "STINGRAY_DECODE_MMQ_BM32",
        "STINGRAY_DECODE_PROFILE",
        "STINGRAY_DECODE_REGIONS",
        "STINGRAY_DENSE_FFN_GPU_MARGIN_MB",
        "STINGRAY_DISABLE_BATCH_VERIFY",
        "STINGRAY_DISABLE_DUAL_Q8",
        "STINGRAY_DISABLE_MTP",
        "STINGRAY_DSPARK_MIN_CONFIDENCE",
        "STINGRAY_DSPARK_MODEL",
        "STINGRAY_DSPARK_PLACE",
        "STINGRAY_DSPARK_TIMING",
        "STINGRAY_DSPARK_VERIFY_LEN",
        "STINGRAY_EXPERT_STATS",
        "STINGRAY_FLASH64_STRIDED_GEMM",
        "STINGRAY_FORCE_CPU_EMBED",
        "STINGRAY_FORCE_NO_BLAS",
        "STINGRAY_GDN_CHUNKED_PREFILL",
        "STINGRAY_GDN_DECODE_FAST",
        "STINGRAY_GDN_PREFILL_COMPUTE",
        "STINGRAY_GDN_RAW_Q8_0",
        "STINGRAY_GEMM_PATH",
        "STINGRAY_GEMMA4_PROBE",
        "STINGRAY_GPU_ARGMAX",
        "STINGRAY_HYBRID_BATCHED_MOE",
        "STINGRAY_HYBRID_PREFILL_COMPUTE",
        "STINGRAY_KVARN_BATCHED_PREFILL",
        "STINGRAY_KV_BF16_MIN_TOKENS",
        "STINGRAY_KV_BUDGET_MB",
        "STINGRAY_KV_DTYPE",
        "STINGRAY_KV_STORE",
        "STINGRAY_MATVEC_WIDE8",
        "STINGRAY_MAX_BATCH",
        "STINGRAY_MAX_CONCURRENT",
        "STINGRAY_MAX_QUEUE",
        // STINGRAY_MAX_QUEUED_REQUESTS was here but nothing ever read it — it is the name of the
        // OPTION (options.MaxQueuedRequests), which STINGRAY_MAX_QUEUE above sets. Registering it
        // made things worse rather than harmless: `doctor` treats registry names as valid, so an
        // operator who followed the old overload warning and set it got no "unknown variable"
        // hint. Removed so the typo is reported and SuggestClosest points at STINGRAY_MAX_QUEUE.
        "STINGRAY_MIN_BATCH_BLAS",
        "STINGRAY_MMPROJ",
        "STINGRAY_MMQ_SOA",
        "STINGRAY_MODEL",
        "STINGRAY_MOE_BATCHED_PREFILL",
        "STINGRAY_MOE_GPU_PREFILL",
        "STINGRAY_MOE_GPU_PREFILL_MIN_TOKENS",
        "STINGRAY_MOE_GPU_ROUTER",
        "STINGRAY_MOE_PIN_MODE",
        "STINGRAY_MOE_PREDICT_PREFETCH",
        "STINGRAY_MOE_THREADS",
        "STINGRAY_MOE_WARMPIN",
        "STINGRAY_MOE_WARMPIN_AFTER",
        "STINGRAY_MTP_BATCHED_MOE_VERIFY",
        "STINGRAY_MTP_BATCH_MAX",
        "STINGRAY_MTP_DRAFT_N",
        "STINGRAY_MTP_MIN_ACCEPT",
        "STINGRAY_MTP_PROBE_STEPS",
        "STINGRAY_NO_THINKING",
        "STINGRAY_N_GPU_LAYERS",
        "STINGRAY_PER_LAYER_HD_PREFILL",
        "STINGRAY_PLE_GPU_DEQUANT",
        "STINGRAY_PREFAULT",
        "STINGRAY_PREFILL_ATTN_FLASH64",
        "STINGRAY_PREFILL_ATTN_FLASH64_TILE_JOBS",
        "STINGRAY_PREFILL_ATTN_WIDE_HEADS",
        "STINGRAY_PREFILL_ATTN_KV_OUTER",
        "STINGRAY_PREFILL_ATTN_KV_OUTER_TILES",
        "STINGRAY_PREFILL_ATTN_REGISTER_VALUES",
        "STINGRAY_PREFILL_CHUNK",
        "STINGRAY_PREFILL_DEQUANT_MB",
        "STINGRAY_PREFILL_FLASH",
        "STINGRAY_PREFILL_FLASH_TC",
        "STINGRAY_PREFILL_FLASH_TC1",
        "STINGRAY_PREFILL_GEMM",
        "STINGRAY_PREFILL_MMQ",
        "STINGRAY_PREFILL_PROFILE",
        "STINGRAY_PREFIX_CACHE_MB",
        "STINGRAY_PREFIX_SCRATCH_TOKENS",
        "STINGRAY_PREFIX_SLOTS",
        "STINGRAY_PRESERVE_THINKING",
        "STINGRAY_PROBE_IDS",
        "STINGRAY_PROBE_LOGITS",
        "STINGRAY_PROBE_POS",
        "STINGRAY_PROFILE_DECODE",
        "STINGRAY_PROFILE_PREFILL",
        "STINGRAY_Q3K_DEQUANT_GEMM",
        "STINGRAY_Q3K_Q8K",
        "STINGRAY_Q40_DP4A",
        "STINGRAY_Q4KX8_CACHE_MB",
        "STINGRAY_Q4K_Q8K",
        "STINGRAY_Q4K_SOA",
        "STINGRAY_Q6K_DECODE_MMQ",
        "STINGRAY_Q6K_SOA",
        "STINGRAY_Q80_DP4A",
        "STINGRAY_Q8_0_Q8K",
        "STINGRAY_RAW_PROMPT",
        "STINGRAY_SDCPP",
        "STINGRAY_SNAPKV_BUDGET",
        "STINGRAY_SNAPKV_RECENCY",
        "STINGRAY_SNAPKV_WINDOW",
        "STINGRAY_SPEC_BATCH_VERIFY",
        "STINGRAY_SPEC_SAMPLE",
        "STINGRAY_SPLIT_DECODE",
        "STINGRAY_SPLIT_DECODE_GROUPED",
        "STINGRAY_TOOL_GRAMMAR",
        "STINGRAY_TQ",
        "STINGRAY_TQ_MODE",
        "STINGRAY_TRACE_DSPARK",
        "STINGRAY_TRACE_GDN_INTERNAL",
        "STINGRAY_TRACE_GDN_LAYERS",
        "STINGRAY_TRACE_GDN_POS",
        "STINGRAY_TRACE_LAYERS",
        "STINGRAY_TRACE_MTP",
        "STINGRAY_TRACE_NORMS",
        "STINGRAY_TRACE_POS",
        "STINGRAY_TRACE_ROUTERS",
        "STINGRAY_TRACE_SNAPSHOT",
        "STINGRAY_TRACE_VRAM",
        "STINGRAY_TRUNK_MATVEC_FAST",
        "STINGRAY_VULKAN_BATCHED_PREFILL",
        "STINGRAY_VULKAN_DP4A",
        "STINGRAY_VULKAN_GDN_CHUNKED_PREFILL",
        "STINGRAY_VULKAN_MM_PATH",
        "STINGRAY_VULKAN_MM_STATS",
        "STINGRAY_VULKAN_PATH2",
        "STINGRAY_VULKAN_PATH2_EXPERIMENTAL",
        "STINGRAY_VULKAN_NO_BATCHED_PREFILL",
        "STINGRAY_VULKAN_PREFILL_CHUNK",
        "STINGRAY_VULKAN_NO_FLASH_ATTN",
        "STINGRAY_VULKAN_SPLIT_DECODE",
        "STINGRAY_VULKAN_SPLIT_DECODE_MIN",
        "STINGRAY_VULKAN_UMA_FRACTION",
        "STINGRAY_VULKAN_VALIDATION",
    }.ToFrozenSet(StringComparer.Ordinal);

    /// <summary>
    /// Returns any <c>STINGRAY_*</c> variables present in <paramref name="environment"/> that the
    /// engine never reads — almost always a typo or a setting from a different version. Sorted for
    /// deterministic output.
    /// </summary>
    public static IReadOnlyList<string> FindUnknown(IEnumerable<string> environment)
    {
        List<string>? unknown = null;
        foreach (string key in environment)
        {
            if (!key.StartsWith(Prefix, StringComparison.Ordinal)) continue;
            if (All.Contains(key)) continue;
            (unknown ??= []).Add(key);
        }
        if (unknown is null) return [];
        unknown.Sort(StringComparer.Ordinal);
        return unknown;
    }

    /// <summary>Convenience overload reading the current process environment.</summary>
    public static IReadOnlyList<string> FindUnknown()
    {
        var keys = new List<string>();
        foreach (System.Collections.DictionaryEntry e in Environment.GetEnvironmentVariables())
            if (e.Key is string k) keys.Add(k);
        return FindUnknown(keys);
    }

    /// <summary>
    /// Best-effort "did you mean" for an unknown name: the known variable with the smallest
    /// Levenshtein distance, when that distance is small enough to be a plausible typo.
    /// </summary>
    public static string? SuggestClosest(string unknown)
    {
        // Compare only the part AFTER the shared prefix. Every name begins with the same 12
        // characters, so including them makes every pair look similar and produces confidently
        // wrong suggestions — "..._HF_TOKEN" was matched to "..._TQ_MODE" before this.
        string unknownSuffix = Suffix(unknown);
        if (unknownSuffix.Length == 0) return null;

        string? best = null;
        int bestDistance = int.MaxValue;
        foreach (string candidate in All)
        {
            int d = Distance(unknownSuffix, Suffix(candidate), bestDistance);
            if (d < bestDistance) { bestDistance = d; best = candidate; }
        }

        // A third of the suffix length, floor 2. Tuned so a one- or two-character slip on a real
        // name still resolves, while an unrelated name suggests nothing at all.
        int threshold = Math.Max(2, unknownSuffix.Length / 3);
        return bestDistance <= threshold ? best : null;
    }

    private static string Suffix(string name) =>
        name.StartsWith(Prefix, StringComparison.Ordinal) ? name[Prefix.Length..] : name;

    private static int Distance(string a, string b, int cutoff)
    {
        if (Math.Abs(a.Length - b.Length) >= cutoff) return int.MaxValue;
        Span<int> prev = stackalloc int[b.Length + 1];
        Span<int> cur = stackalloc int[b.Length + 1];
        for (int j = 0; j <= b.Length; j++) prev[j] = j;
        for (int i = 1; i <= a.Length; i++)
        {
            cur[0] = i;
            int rowMin = cur[0];
            for (int j = 1; j <= b.Length; j++)
            {
                int cost = a[i - 1] == b[j - 1] ? 0 : 1;
                cur[j] = Math.Min(Math.Min(cur[j - 1] + 1, prev[j] + 1), prev[j - 1] + cost);
                if (cur[j] < rowMin) rowMin = cur[j];
            }
            if (rowMin >= cutoff) return int.MaxValue;   // cannot beat the incumbent
            prev = cur.ToArray();
        }
        return prev[b.Length];
    }
}
