using System.Numerics.Tensors;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

namespace OpenTail.Stingray.Audio.Chatterbox;

/// <summary>
/// Native C# 24-layer GPT2-medium-architecture Autoregressive Acoustic Language Model ("T3") for
/// Chatterbox-Turbo TTS, ported from examples/chatterbox-tts-py/chatterbox/models/t3/t3.py
/// (T3.forward/prepare_input_embeds/inference_turbo) and llama_configs.py's GPT2_MEDIUM_CONFIG.
/// Generates discrete speech tokens conditioned on a projected speaker embedding and a fixed-length
/// bank of speech "prompt" tokens (both baked into the GGUF as the built-in default voice), using a
/// standard pre-LN GPT2 transformer body with absolute (wpe) position embeddings, fused QKV, and
/// gelu_new-activated MLP. When no real weights are supplied, falls back to the original
/// placeholder/synthetic generator (kept for the parameterless/no-model test and demo path).
/// </summary>
public sealed class ChatterboxAcousticLm : IDisposable
{
    public const int HiddenDim = 1024;
    public const int NumLayers = 24;
    public const int NumHeads = 16;
    public const int HeadDim = HiddenDim / NumHeads; // 64
    public const int VocabSize = 8192;
    public const int StartSpeechToken = 6561;
    public const int StopSpeechToken = 6562;

    public float RepetitionPenalty { get; set; } = 1.2f;
    public int TopK { get; set; } = 1000;
    public float TopP { get; set; } = 0.95f;

    private readonly ChatterboxWeights? _weights;
    private readonly Random _rng;

    public ChatterboxAcousticLm(ChatterboxWeights? weights = null, Random? rng = null)
    {
        _weights = weights;
        _rng = rng ?? Random.Shared;
    }

    /// <summary>
    /// Autoregressively synthesizes discrete speech tokens from text token sequence. Uses the real
    /// GPT2 T3 transformer when real weights were supplied at construction; otherwise falls back to
    /// the original synthetic placeholder generator.
    /// </summary>
    public List<int> GenerateSpeechTokens(
        ReadOnlySpan<int> textTokens,
        float[] speakerFeatures,
        float temperature = 0.7f,
        int maxTokens = 512)
    {
        if (_weights is { } w)
            return GenerateReal(w, textTokens, temperature, maxTokens);

        return GenerateFakePlaceholder(textTokens, speakerFeatures, temperature, maxTokens);
    }

    /// <summary>
    /// Yields discrete speech tokens one-by-one as they are generated by the T3 transformer.
    /// </summary>
    public IEnumerable<int> GenerateSpeechTokensStream(
        int[] textTokens,
        float[] speakerFeatures,
        float temperature = 0.7f,
        int maxTokens = 512)
    {
        if (_weights is { } w)
        {
            foreach (var tok in GenerateRealStream(w, textTokens, temperature, maxTokens))
                yield return tok;
            yield break;
        }

        foreach (var tok in GenerateFakePlaceholder(textTokens, speakerFeatures, temperature, maxTokens))
            yield return tok;
    }

    // -----------------------------------------------------------------------
    // Reusable Zero-Alloc Workspace for Transformer Decode Step
    // -----------------------------------------------------------------------

    private sealed class T3Workspace
    {
        public readonly float[] Hidden;
        public readonly float[] AttnNormed;
        public readonly float[] Qkv;
        public readonly float[] Context;
        public readonly float[] AttnOut;
        public readonly float[] FfnNormed;
        public readonly float[] Fc;
        public readonly float[] Proj;
        public readonly float[] FinalHidden;
        public readonly float[] Logits;
        public readonly float[] Scores;
        public readonly (float val, int idx)[] TopKIndexBuf;
        public readonly double[] ExpVals;

        public T3Workspace(int hiddenDim, int intermediateSize, int vocabSize, int maxPositions)
        {
            Hidden = new float[hiddenDim];
            AttnNormed = new float[hiddenDim];
            Qkv = new float[3 * hiddenDim];
            Context = new float[hiddenDim];
            AttnOut = new float[hiddenDim];
            FfnNormed = new float[hiddenDim];
            Fc = new float[intermediateSize];
            Proj = new float[hiddenDim];
            FinalHidden = new float[hiddenDim];
            Logits = new float[vocabSize];
            Scores = new float[maxPositions];
            TopKIndexBuf = new (float val, int idx)[vocabSize];
            ExpVals = new double[vocabSize];
        }
    }

    // -----------------------------------------------------------------------
    // Real T3 GPT2 inference (inference_turbo)
    // -----------------------------------------------------------------------

    private IEnumerable<int> GenerateRealStream(ChatterboxWeights w, int[] textTokens, float temperature, int maxTokens)
    {
        int startSpeech = w.StartSpeechToken;
        int stopSpeech = w.StopSpeechToken;

        var condEmbeds = new List<float[]>(1 + w.SpeechCondPromptLen);
        float[] speakerEmb = w.SpeakerEmbedding ?? new float[w.SpeakerEmbedSize];
        condEmbeds.Add(Linear(speakerEmb, w.SpkrEncWeight, w.SpkrEncBias, w.SpeakerEmbedSize, w.HiddenDim));

        if (w.SpeechPromptTokens is { } promptTokens)
        {
            foreach (int tok in promptTokens)
                condEmbeds.Add(EmbedRow(w.SpeechEmbWeight, tok, w.HiddenDim));
        }

        var chunk = new List<float[]>(condEmbeds.Count + textTokens.Length + 1);
        chunk.AddRange(condEmbeds);
        foreach (int tok in textTokens)
            chunk.Add(EmbedRow(w.TextEmbWeight, tok, w.HiddenDim));

        chunk.Add(EmbedRow(w.SpeechEmbWeight, startSpeech, w.HiddenDim));

        int maxPositions = chunk.Count + maxTokens + 16;
        var kCacheFlat = new float[w.NumLayers][];
        var vCacheFlat = new float[w.NumLayers][];
        for (int l = 0; l < w.NumLayers; l++)
        {
            kCacheFlat[l] = new float[maxPositions * w.HiddenDim];
            vCacheFlat[l] = new float[maxPositions * w.HiddenDim];
        }

        var workspace = new T3Workspace(w.HiddenDim, w.IntermediateSize, w.SpeechVocabSize, maxPositions);

        float[][] hidden = ProcessChunk(w, chunk.ToArray(), startPos: 0, kCacheFlat, vCacheFlat);
        int pos = chunk.Count;

        var speechTokens = new List<int>();
        float[] lastHidden = hidden[^1];
        int nextToken = SampleNext(w, lastHidden, speechTokens, temperature, workspace);
        if (nextToken != stopSpeech)
        {
            speechTokens.Add(nextToken);
            yield return nextToken;
        }

        for (int step = 1; step < maxTokens; step++)
        {
            if (nextToken == stopSpeech) break;

            DecodeStep(w, nextToken, pos, kCacheFlat, vCacheFlat, workspace);
            pos++;

            nextToken = SampleNext(w, workspace.FinalHidden, speechTokens, temperature, workspace);
            if (nextToken == stopSpeech) break;
            speechTokens.Add(nextToken);
            yield return nextToken;
        }
    }

    private List<int> GenerateReal(ChatterboxWeights w, ReadOnlySpan<int> textTokens, float temperature, int maxTokens)
    {
        int startSpeech = w.StartSpeechToken;
        int stopSpeech = w.StopSpeechToken;

        // --- Assemble conditioning embeds: [spkr_proj(1), speech_emb(prompt_tokens)(SpeechCondPromptLen)] ---
        var condEmbeds = new List<float[]>(1 + w.SpeechCondPromptLen);
        float[] speakerEmb = w.SpeakerEmbedding ?? new float[w.SpeakerEmbedSize];
        condEmbeds.Add(Linear(speakerEmb, w.SpkrEncWeight, w.SpkrEncBias, w.SpeakerEmbedSize, w.HiddenDim));

        if (w.SpeechPromptTokens is { } promptTokens)
        {
            foreach (int tok in promptTokens)
                condEmbeds.Add(EmbedRow(w.SpeechEmbWeight, tok, w.HiddenDim));
        }

        // --- Text embeds ---
        var chunk = new List<float[]>(condEmbeds.Count + textTokens.Length + 1);
        chunk.AddRange(condEmbeds);
        foreach (int tok in textTokens)
            chunk.Add(EmbedRow(w.TextEmbWeight, tok, w.HiddenDim));

        // --- Initial speech token (BOS = start_speech_token) ---
        chunk.Add(EmbedRow(w.SpeechEmbWeight, startSpeech, w.HiddenDim));

        int maxPositions = chunk.Count + maxTokens + 16;
        var kCacheFlat = new float[w.NumLayers][];
        var vCacheFlat = new float[w.NumLayers][];
        for (int l = 0; l < w.NumLayers; l++)
        {
            kCacheFlat[l] = new float[maxPositions * w.HiddenDim];
            vCacheFlat[l] = new float[maxPositions * w.HiddenDim];
        }

        var workspace = new T3Workspace(w.HiddenDim, w.IntermediateSize, w.SpeechVocabSize, maxPositions);

        // Prefill: process the whole [cond, text, BOS] chunk at once.
        float[][] hidden = ProcessChunk(w, chunk.ToArray(), startPos: 0, kCacheFlat, vCacheFlat);
        int pos = chunk.Count;

        var speechTokens = new List<int>();
        float[] lastHidden = hidden[^1];
        int nextToken = SampleNext(w, lastHidden, speechTokens, temperature, workspace);
        speechTokens.Add(nextToken);

        for (int step = 1; step < maxTokens; step++)
        {
            if (nextToken == stopSpeech) break;

            DecodeStep(w, nextToken, pos, kCacheFlat, vCacheFlat, workspace);
            pos++;

            nextToken = SampleNext(w, workspace.FinalHidden, speechTokens, temperature, workspace);
            speechTokens.Add(nextToken);
        }

        // Drop a trailing EOS if present (matches inference_turbo's post-processing).
        if (speechTokens.Count > 0 && speechTokens[^1] == stopSpeech)
            speechTokens.RemoveAt(speechTokens.Count - 1);

        var result = new List<int>(speechTokens.Count + 2) { startSpeech };
        result.AddRange(speechTokens);
        result.Add(stopSpeech);
        return result;
    }

    /// <summary>
    /// High-performance zero-allocation single-token decode step.
    /// Computes transformer layer transformations in-place, writes directly to flat KV cache,
    /// and populates workspace.FinalHidden for logits sampling.
    /// </summary>
    private static unsafe void DecodeStep(
        ChatterboxWeights w,
        int token,
        int pos,
        float[][] kCacheFlat,
        float[][] vCacheFlat,
        T3Workspace ws)
    {
        int dim = w.HiddenDim;
        int intermediateSize = w.IntermediateSize;
        float scale = 1f / MathF.Sqrt(HeadDim);

        fixed (float* speechEmb = w.SpeechEmbWeight, wpe = w.WpeWeight, hidden = ws.Hidden,
                      attnNormed = ws.AttnNormed, qkv = ws.Qkv, ctxBase = ws.Context,
                      attnOut = ws.AttnOut, ffnNormed = ws.FfnNormed, fc = ws.Fc,
                      proj = ws.Proj, finalHidden = ws.FinalHidden, scores = ws.Scores)
        {
            // 1. Initial embedding: hidden = speech_emb[token] + wpe[pos]
            float* embRow = speechEmb + (long)token * dim;
            float* wpeRow = wpe + (long)pos * dim;
            TensorPrimitives.Add(new ReadOnlySpan<float>(embRow, dim), new ReadOnlySpan<float>(wpeRow, dim), new Span<float>(hidden, dim));

            int availableKeys = pos + 1;

            // 2. Transformer layers
            for (int l = 0; l < w.NumLayers; l++)
            {
                var layer = w.Layers[l];
                fixed (float* kFlat = kCacheFlat[l], vFlat = vCacheFlat[l],
                              anw = layer.AttnNormWeight, anb = layer.AttnNormBias,
                              qkvw = layer.AttnQkvWeight, qkvb = layer.AttnQkvBias,
                              aow = layer.AttnOutputWeight, aob = layer.AttnOutputBias,
                              fnw = layer.FfnNormWeight, fnb = layer.FfnNormBias,
                              fcw = layer.FfnFcWeight, fcb = layer.FfnFcBias,
                              prw = layer.FfnProjWeight, prb = layer.FfnProjBias)
                {
                    // --- Self-Attention ---
                    SimdKernels.LayerNorm(attnNormed, hidden, anw, anb, dim, 1e-5f);
                    SimdKernels.MatVecF32(qkv, qkvw, qkvb, attnNormed, 3 * dim, dim);

                    float* qPtr = qkv;
                    float* kDest = kFlat + (long)pos * dim;
                    float* vDest = vFlat + (long)pos * dim;
                    UnsafeCopy(qkv + dim, kDest, dim);
                    UnsafeCopy(qkv + 2 * dim, vDest, dim);

                    // Attention context per head
                    for (int h = 0; h < NumHeads; h++)
                    {
                        int hOff = h * HeadDim;
                        float* qHead = qPtr + hOff;
                        float* cHead = ctxBase + hOff;

                        for (int t = 0; t < availableKeys; t++)
                        {
                            float* kt = kFlat + (long)t * dim + hOff;
                            scores[t] = SimdKernels.DotF32(qHead, kt, HeadDim) * scale;
                        }

                        SoftmaxInPlace(new Span<float>(scores, availableKeys));

                        if (HeadDim == 64 && Avx.IsSupported && Fma.IsSupported)
                        {
                            var c0 = Vector256<float>.Zero;
                            var c1 = Vector256<float>.Zero;
                            var c2 = Vector256<float>.Zero;
                            var c3 = Vector256<float>.Zero;
                            var c4 = Vector256<float>.Zero;
                            var c5 = Vector256<float>.Zero;
                            var c6 = Vector256<float>.Zero;
                            var c7 = Vector256<float>.Zero;

                            for (int t = 0; t < availableKeys; t++)
                            {
                                float p = scores[t];
                                if (p == 0f) continue;
                                var pVec = Vector256.Create(p);
                                float* vRow = vFlat + (long)t * dim + hOff;
                                c0 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow), c0);
                                c1 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 8), c1);
                                c2 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 16), c2);
                                c3 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 24), c3);
                                c4 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 32), c4);
                                c5 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 40), c5);
                                c6 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 48), c6);
                                c7 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 56), c7);
                            }

                            Avx.Store(cHead, c0);
                            Avx.Store(cHead + 8, c1);
                            Avx.Store(cHead + 16, c2);
                            Avx.Store(cHead + 24, c3);
                            Avx.Store(cHead + 32, c4);
                            Avx.Store(cHead + 40, c5);
                            Avx.Store(cHead + 48, c6);
                            Avx.Store(cHead + 56, c7);
                        }
                        else
                        {
                            for (int d = 0; d < HeadDim; d++) cHead[d] = 0f;
                            for (int t = 0; t < availableKeys; t++)
                            {
                                float p = scores[t];
                                if (p == 0f) continue;
                                float* vRow = vFlat + (long)t * dim + hOff;
                                for (int d = 0; d < HeadDim; d++) cHead[d] += p * vRow[d];
                            }
                        }
                    }

                    // Attn output + residual
                    SimdKernels.MatVecF32(attnOut, aow, aob, ctxBase, dim, dim);
                    TensorPrimitives.Add(new ReadOnlySpan<float>(hidden, dim), new ReadOnlySpan<float>(attnOut, dim), new Span<float>(hidden, dim));

                    // --- MLP Block ---
                    SimdKernels.LayerNorm(ffnNormed, hidden, fnw, fnb, dim, 1e-5f);
                    SimdKernels.MatVecF32(fc, fcw, fcb, ffnNormed, intermediateSize, dim);
                    GeluNewInPlace(fc, intermediateSize);
                    SimdKernels.MatVecF32(proj, prw, prb, fc, dim, intermediateSize);
                    TensorPrimitives.Add(new ReadOnlySpan<float>(hidden, dim), new ReadOnlySpan<float>(proj, dim), new Span<float>(hidden, dim));
                }
            }

            // 3. Final Output LayerNorm
            fixed (float* onw = w.OutputNormWeight, onb = w.OutputNormBias)
            {
                SimdKernels.LayerNorm(finalHidden, hidden, onw, onb, dim, 1e-5f);
            }
        }
    }

    private static unsafe void UnsafeCopy(float* src, float* dst, int count)
    {
        Buffer.MemoryCopy(src, dst, (long)count * sizeof(float), (long)count * sizeof(float));
    }

    private int SampleNext(ChatterboxWeights w, float[] hidden, List<int> historySoFar, float temperature, T3Workspace? ws = null)
    {
        float[] logits;
        if (ws != null)
        {
            logits = ws.Logits;
            unsafe
            {
                fixed (float* lp = logits, hp = hidden, wp = w.SpeechHeadWeight, bp = w.SpeechHeadBias)
                {
                    SimdKernels.MatVecF32(lp, wp, bp, hp, w.SpeechVocabSize, w.HiddenDim);
                }
            }
        }
        else
        {
            logits = Linear(hidden, w.SpeechHeadWeight, w.SpeechHeadBias, w.HiddenDim, w.SpeechVocabSize);
        }

        // Repetition penalty -> Temperature -> top-k -> top-p
        ApplyRepetitionPenalty(logits, historySoFar, RepetitionPenalty);
        ApplyTemperature(logits, temperature);
        ApplyTopK(logits, TopK, ws?.TopKIndexBuf);
        ApplyTopP(logits, TopP, ws?.TopKIndexBuf, ws?.ExpVals);

        return SampleFromLogits(logits);
    }

    private static void ApplyTemperature(float[] logits, float temperature)
    {
        if (temperature is <= 0f or 1f) return;
        for (int i = 0; i < logits.Length; i++) logits[i] /= temperature;
    }

    private static void ApplyTopK(float[] logits, int topK, (float val, int idx)[]? buffer = null)
    {
        if (topK <= 0 || topK >= logits.Length) return;
        var indexed = buffer ?? new (float val, int idx)[logits.Length];
        for (int i = 0; i < logits.Length; i++) indexed[i] = (logits[i], i);
        Array.Sort(indexed, 0, logits.Length, Comparer<(float val, int idx)>.Create((a, b) => b.val.CompareTo(a.val)));
        for (int i = topK; i < indexed.Length; i++) logits[indexed[i].idx] = float.NegativeInfinity;
    }

    private static void ApplyTopP(float[] logits, float topP, (float val, int idx)[]? idxBuffer = null, double[]? expBuffer = null)
    {
        if (topP >= 1f) return;
        int n = logits.Length;
        var indexed = idxBuffer ?? new (float val, int idx)[n];
        for (int i = 0; i < n; i++) indexed[i] = (logits[i], i);
        Array.Sort(indexed, 0, n, Comparer<(float val, int idx)>.Create((a, b) => b.val.CompareTo(a.val)));

        float max = indexed[0].val;
        if (float.IsNegativeInfinity(max)) return;
        double sumExp = 0;
        var expVals = expBuffer ?? new double[n];
        for (int i = 0; i < n; i++)
        {
            expVals[i] = float.IsNegativeInfinity(indexed[i].val) ? 0.0 : Math.Exp(indexed[i].val - max);
            sumExp += expVals[i];
        }

        double cumulative = 0;
        for (int i = 0; i < n; i++)
        {
            double prob = expVals[i] / sumExp;
            cumulative += prob;
            // Keep the smallest prefix whose cumulative probability >= topP; always keep at least 1.
            if (i > 0 && cumulative - prob >= topP)
                logits[indexed[i].idx] = float.NegativeInfinity;
        }
    }

    private static void ApplyRepetitionPenalty(float[] logits, List<int> history, float penalty)
    {
        if (penalty == 1f || history.Count == 0) return;
        foreach (int tok in history)
        {
            if ((uint)tok >= (uint)logits.Length) continue;
            float score = logits[tok];
            if (float.IsNegativeInfinity(score)) continue;
            logits[tok] = score > 0f ? score / penalty : score * penalty;
        }
    }

    private int SampleFromLogits(float[] logits)
    {
        float max = float.NegativeInfinity;
        for (int i = 0; i < logits.Length; i++) if (logits[i] > max) max = logits[i];
        if (float.IsNegativeInfinity(max)) return 0;

        double sum = 0;
        for (int i = 0; i < logits.Length; i++)
        {
            double p = float.IsNegativeInfinity(logits[i]) ? 0.0 : Math.Exp(logits[i] - max);
            sum += p;
        }

        double r = _rng.NextDouble() * sum;
        double acc = 0;
        for (int i = 0; i < logits.Length; i++)
        {
            double p = float.IsNegativeInfinity(logits[i]) ? 0.0 : Math.Exp(logits[i] - max);
            acc += p;
            if (acc >= r) return i;
        }
        return logits.Length - 1;
    }

    /// <summary>
    /// Runs the GPT2 body over a chunk of already-embedded positions (prefill),
    /// appending this chunk's K/V to the running flat cache and returning each
    /// position's post-final-LayerNorm hidden state (t3.output_norm, i.e. GPT2Model's ln_f).
    /// </summary>
    private static unsafe float[][] ProcessChunk(
        ChatterboxWeights w,
        float[][] chunkEmbeds,
        int startPos,
        float[][] kCacheFlat,
        float[][] vCacheFlat)
    {
        int n = chunkEmbeds.Length;
        int dim = w.HiddenDim;

        // hidden_states = inputs_embeds + wpe[position]  (GPT2Model.forward)
        var hidden = new float[n][];
        for (int i = 0; i < n; i++)
        {
            var h = new float[dim];
            int posRow = (startPos + i) * dim;
            TensorPrimitives.Add(chunkEmbeds[i], w.WpeWeight.AsSpan(posRow, dim), h);
            hidden[i] = h;
        }

        for (int l = 0; l < w.NumLayers; l++)
        {
            var layer = w.Layers[l];
            float[] kFlat = kCacheFlat[l];
            float[] vFlat = vCacheFlat[l];

            // --- Self-attention block ---
            var attnNormed = new float[n][];
            for (int i = 0; i < n; i++)
                attnNormed[i] = LayerNorm(hidden[i], layer.AttnNormWeight, layer.AttnNormBias);
            var qkvAll = LinearBatched(attnNormed, layer.AttnQkvWeight, layer.AttnQkvBias, dim, 3 * dim);

            for (int i = 0; i < n; i++)
            {
                int pos = startPos + i;
                Array.Copy(qkvAll[i], dim, kFlat, (long)pos * dim, dim);
                Array.Copy(qkvAll[i], 2 * dim, vFlat, (long)pos * dim, dim);
            }

            var contexts = new float[n][];
            float scale = 1f / MathF.Sqrt(HeadDim);

            Parallel.For(0, n, i =>
            {
                int selfCachePos = startPos + i;
                int availableKeys = selfCachePos + 1;
                var q = qkvAll[i];
                var context = new float[dim];
                var scores = new float[availableKeys];

                fixed (float* qp = q, ctxBase = context, sp = scores, kF = kFlat, vF = vFlat)
                {
                    for (int h = 0; h < NumHeads; h++)
                    {
                        int hOff = h * HeadDim;
                        float* qHead = qp + hOff;
                        float* cHead = ctxBase + hOff;

                        for (int t = 0; t < availableKeys; t++)
                        {
                            float* kt = kF + (long)t * dim + hOff;
                            sp[t] = SimdKernels.DotF32(qHead, kt, HeadDim) * scale;
                        }

                        SoftmaxInPlace(new Span<float>(sp, availableKeys));

                        if (HeadDim == 64 && Avx.IsSupported && Fma.IsSupported)
                        {
                            var c0 = Vector256<float>.Zero;
                            var c1 = Vector256<float>.Zero;
                            var c2 = Vector256<float>.Zero;
                            var c3 = Vector256<float>.Zero;
                            var c4 = Vector256<float>.Zero;
                            var c5 = Vector256<float>.Zero;
                            var c6 = Vector256<float>.Zero;
                            var c7 = Vector256<float>.Zero;

                            for (int t = 0; t < availableKeys; t++)
                            {
                                float p = sp[t];
                                if (p == 0f) continue;
                                var pVec = Vector256.Create(p);
                                float* vRow = vF + (long)t * dim + hOff;
                                c0 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow), c0);
                                c1 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 8), c1);
                                c2 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 16), c2);
                                c3 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 24), c3);
                                c4 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 32), c4);
                                c5 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 40), c5);
                                c6 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 48), c6);
                                c7 = Fma.MultiplyAdd(pVec, Avx.LoadVector256(vRow + 56), c7);
                            }

                            Avx.Store(cHead, c0);
                            Avx.Store(cHead + 8, c1);
                            Avx.Store(cHead + 16, c2);
                            Avx.Store(cHead + 24, c3);
                            Avx.Store(cHead + 32, c4);
                            Avx.Store(cHead + 40, c5);
                            Avx.Store(cHead + 48, c6);
                            Avx.Store(cHead + 56, c7);
                        }
                        else
                        {
                            for (int d = 0; d < HeadDim; d++) cHead[d] = 0f;
                            for (int t = 0; t < availableKeys; t++)
                            {
                                float p = sp[t];
                                if (p == 0f) continue;
                                float* vRow = vF + (long)t * dim + hOff;
                                for (int d = 0; d < HeadDim; d++) cHead[d] += p * vRow[d];
                            }
                        }
                    }
                }
                contexts[i] = context;
            });

            var attnOut = LinearBatched(contexts, layer.AttnOutputWeight, layer.AttnOutputBias, dim, dim);

            for (int i = 0; i < n; i++)
                TensorPrimitives.Add(hidden[i], attnOut[i], hidden[i]);

            // --- MLP block ---
            var ffnNormed = new float[n][];
            for (int i = 0; i < n; i++)
                ffnNormed[i] = LayerNorm(hidden[i], layer.FfnNormWeight, layer.FfnNormBias);
            var fcAll = LinearBatched(ffnNormed, layer.FfnFcWeight, layer.FfnFcBias, dim, w.IntermediateSize);
            for (int i = 0; i < n; i++)
            {
                fixed (float* fcp = fcAll[i])
                {
                    GeluNewInPlace(fcp, w.IntermediateSize);
                }
            }
            var projAll = LinearBatched(fcAll, layer.FfnProjWeight, layer.FfnProjBias, w.IntermediateSize, dim);
            for (int i = 0; i < n; i++)
                TensorPrimitives.Add(hidden[i], projAll[i], hidden[i]);
        }

        // Final LayerNorm (ln_f / t3.output_norm).
        var result = new float[n][];
        for (int i = 0; i < n; i++)
            result[i] = LayerNorm(hidden[i], w.OutputNormWeight, w.OutputNormBias);
        return result;
    }

    private static float[] EmbedRow(float[] table, int index, int dim)
    {
        var row = new float[dim];
        Array.Copy(table, (long)index * dim, row, 0, dim);
        return row;
    }

    private static unsafe float[] Linear(float[] input, float[] weight, float[] bias, int inDim, int outDim)
    {
        var output = new float[outDim];
        fixed (float* w = weight, x = input, y = output, b = bias)
        {
            SimdKernels.MatVecF32(y, w, b, x, outDim, inDim);
        }
        return output;
    }

    private static unsafe float[][] LinearBatched(float[][] inputs, float[] weight, float[] bias, int inDim, int outDim)
    {
        int n = inputs.Length;
        if (n == 1)
        {
            var singleOut = new float[outDim];
            fixed (float* w = weight, x = inputs[0], y = singleOut, b = bias)
            {
                SimdKernels.MatVecF32(y, w, b, x, outDim, inDim);
            }
            return [singleOut];
        }

        var outputs = new float[n][];
        for (int i = 0; i < n; i++) outputs[i] = new float[outDim];

        Parallel.For(0, n, i =>
        {
            fixed (float* w = weight, x = inputs[i], y = outputs[i], b = bias)
            {
                SimdKernels.MatVecF32(y, w, b, x, outDim, inDim);
            }
        });

        return outputs;
    }

    private static unsafe float[] LayerNorm(float[] x, float[] weight, float[] bias, float eps = 1e-5f)
    {
        var output = new float[x.Length];
        fixed (float* xp = x, wp = weight, bp = bias, op = output)
        {
            SimdKernels.LayerNorm(op, xp, wp, bp, x.Length, eps);
        }
        return output;
    }

    /// <summary>float-only (no double promotion) in-place softmax over Span.</summary>
    private static void SoftmaxInPlace(Span<float> scores)
    {
        float max = float.NegativeInfinity;
        for (int i = 0; i < scores.Length; i++) if (scores[i] > max) max = scores[i];
        float sum = 0f;
        for (int i = 0; i < scores.Length; i++)
        {
            float e = MathF.Exp(scores[i] - max);
            scores[i] = e;
            sum += e;
        }
        float invSum = 1f / sum;
        for (int i = 0; i < scores.Length; i++) scores[i] *= invSum;
    }

    private static unsafe void GeluNewInPlace(float* x, int len)
    {
        // gelu_new: 0.5*x*(1+tanh(sqrt(2/pi)*(x+0.044715*x^3))) == x / (1 + exp(-2*sqrt(2/pi)*(x+0.044715*x^3)))
        const float c2 = -1.595769121605731f; // -2 * sqrt(2/pi)
        for (int i = 0; i < len; i++)
        {
            float v = x[i];
            float arg = c2 * v * (1f + 0.044715f * v * v);
            if (arg > 35f)
            {
                x[i] = 0f;
            }
            else if (arg < -35f)
            {
                x[i] = v;
            }
            else
            {
                x[i] = v / (1f + MathF.Exp(arg));
            }
        }
    }

    // -----------------------------------------------------------------------
    // Fallback placeholder (used only when no real GGUF weights are available)
    // -----------------------------------------------------------------------

    private static List<int> GenerateFakePlaceholder(
        ReadOnlySpan<int> textTokens,
        float[] speakerFeatures,
        float temperature,
        int maxTokens)
    {
        var speechTokens = new List<int> { StartSpeechToken };
        var tokenCounts = new Dictionary<int, int>();
        tokenCounts[StartSpeechToken] = 1;

        int numText = textTokens.Length;
        int targetSpeechLength = Math.Clamp(numText * 6, 32, maxTokens);

        for (int step = 0; step < targetSpeechLength; step++)
        {
            float textBias = (step / 6 < numText) ? textTokens[step / 6] * 0.05f : 0f;
            float spkBias = (speakerFeatures != null && speakerFeatures.Length > 0)
                ? speakerFeatures[step % speakerFeatures.Length] * 0.1f
                : 0f;

            int bestToken = 100 + Math.Abs((int)(step * 37 + textBias * 100 + spkBias * 50)) % 1024;

            if (tokenCounts.TryGetValue(bestToken, out int count) && count > 0)
            {
                bestToken = (bestToken + 17) % 2048 + 100;
            }

            speechTokens.Add(bestToken);
            tokenCounts[bestToken] = tokenCounts.GetValueOrDefault(bestToken) + 1;
        }

        speechTokens.Add(StopSpeechToken);
        return speechTokens;
    }

    public void Dispose()
    {
        _weights?.Dispose();
    }
}
