<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenTail.Stingray.Diffusion\OpenTail.Stingray.Diffusion.csproj" />
    <ProjectReference Include="..\..\src\OpenTail.Stingray.Cuda\OpenTail.Stingray.Cuda.csproj" />
    <ProjectReference Include="..\..\src\OpenTail.Stingray.Cpu\OpenTail.Stingray.Cpu.csproj" />
  </ItemGroup>

</Project>
