using System.Text.Json.Serialization;
using OpenTail.Stingray.Server.Endpoints;

namespace OpenTail.Stingray.Server;

/// <summary>
/// Source-generated <see cref="System.Text.Json.Serialization.JsonSerializerContext"/> covering
/// every request/response shape served by the OpenTail.Stingray HTTP endpoints. Registered with
/// ASP.NET Core's JSON pipeline by <see cref="ServiceCollectionExtensions.AddOpenTailStingray"/>,
/// so consumers don't usually need to reference it directly. Made <c>public</c> so AOT-published
/// hosts can chain it onto their own <c>JsonOptions</c> if they add OpenTail.Stingray's endpoints
/// alongside their own routes.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ChatCompletionRequest))]
[JsonSerializable(typeof(OaiMessage[]))]
[JsonSerializable(typeof(OaiTool))]
[JsonSerializable(typeof(OaiTool[]))]
[JsonSerializable(typeof(OaiToolFunction))]
[JsonSerializable(typeof(OaiToolCall))]
[JsonSerializable(typeof(OaiToolCall[]))]
[JsonSerializable(typeof(OaiToolCallFunction))]
[JsonSerializable(typeof(OaiToolCallDelta))]
[JsonSerializable(typeof(OaiToolCallDelta[]))]
[JsonSerializable(typeof(ChatCompletionResponse))]
[JsonSerializable(typeof(CompletionChoice[]))]
[JsonSerializable(typeof(OaiAssistantMessage))]
[JsonSerializable(typeof(ChatUsage))]
[JsonSerializable(typeof(CompletionTokensDetails))]
[JsonSerializable(typeof(ChatCompletionChunk))]
[JsonSerializable(typeof(ChunkChoice[]))]
[JsonSerializable(typeof(ChunkDelta))]
[JsonSerializable(typeof(ModelsResponse))]
[JsonSerializable(typeof(ModelInfo[]))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(ResponseFormat))]
[JsonSerializable(typeof(JsonSchemaSpec))]
[JsonSerializable(typeof(AnthropicMessageRequest))]
[JsonSerializable(typeof(AnthropicThinking))]
[JsonSerializable(typeof(AnthropicTool))]
[JsonSerializable(typeof(AnthropicTool[]))]
[JsonSerializable(typeof(AnthropicMessage[]))]
[JsonSerializable(typeof(AnthropicMessageResponse))]
[JsonSerializable(typeof(AContent[]))]
[JsonSerializable(typeof(AUsage))]
[JsonSerializable(typeof(AMessageStartEvent))]
[JsonSerializable(typeof(AContentBlockStartEvent))]
[JsonSerializable(typeof(AContentBlockDeltaEvent))]
[JsonSerializable(typeof(AMessageDeltaEvent))]
[JsonSerializable(typeof(AContentBlockStopEvent))]
[JsonSerializable(typeof(ATypeOnly))]
[JsonSerializable(typeof(AErrorResponse))]
[JsonSerializable(typeof(HealthStatus))]
[JsonSerializable(typeof(ServerCompatibilitySnapshot))]
[JsonSerializable(typeof(ServerApiSurface))]
[JsonSerializable(typeof(ServerRuntimeCapabilities))]
[JsonSerializable(typeof(ServerFeatureAvailability))]
[JsonSerializable(typeof(ServerEffectiveCompatibilityConfiguration))]
[JsonSerializable(typeof(ServerStatusSnapshot))]
[JsonSerializable(typeof(ServerStatusPlacement))]
[JsonSerializable(typeof(ServerStatusTraffic))]
[JsonSerializable(typeof(ServerStatusLatency))]
[JsonSerializable(typeof(ServerLatencySummary))]
[JsonSerializable(typeof(ServerStatusCache))]
[JsonSerializable(typeof(ServerStatusMemory))]
[JsonSerializable(typeof(ServerStatusBatching))]
[JsonSerializable(typeof(OpenTailResponseTiming))]
[JsonSerializable(typeof(ResponsesRequest))]
[JsonSerializable(typeof(RespObject))]
[JsonSerializable(typeof(RespOutputItem))]
[JsonSerializable(typeof(RespOutputItem[]))]
[JsonSerializable(typeof(RespContentPart))]
[JsonSerializable(typeof(RespContentPart[]))]
[JsonSerializable(typeof(RespUsage))]
[JsonSerializable(typeof(RespCreatedEvent))]
[JsonSerializable(typeof(RespOutputItemAddedEvent))]
[JsonSerializable(typeof(RespContentPartAddedEvent))]
[JsonSerializable(typeof(RespOutputTextDeltaEvent))]
[JsonSerializable(typeof(RespOutputTextDoneEvent))]
[JsonSerializable(typeof(RespOutputItemDoneEvent))]
[JsonSerializable(typeof(RespCompletedEvent))]
[JsonSerializable(typeof(Dictionary<string, float>))]
[JsonSerializable(typeof(TokenizeRequest))]
[JsonSerializable(typeof(TokenizeResponse))]
[JsonSerializable(typeof(DetokenizeRequest))]
[JsonSerializable(typeof(DetokenizeResponse))]
[JsonSerializable(typeof(PropsResponse))]
[JsonSerializable(typeof(SessionResponse))]
[JsonSerializable(typeof(SessionCreateRequest))]
[JsonSerializable(typeof(SessionTurnRequest))]
[JsonSerializable(typeof(SessionTurnResponse))]
[JsonSerializable(typeof(SessionOperationResponse))]
[JsonSerializable(typeof(WireSkillTool))]
[JsonSerializable(typeof(WireSkillTool[]))]
[JsonSerializable(typeof(WireSkillInstruction))]
[JsonSerializable(typeof(WireSkillInstruction[]))]
[JsonSerializable(typeof(WireSkill))]
[JsonSerializable(typeof(WireSkill[]))]
[JsonSerializable(typeof(SessionAttachSkillRequest))]
[JsonSerializable(typeof(SessionSkillResponse))]
[JsonSerializable(typeof(SessionSkillResponse[]))]
[JsonSerializable(typeof(SessionSkillsResponse))]
[JsonSerializable(typeof(SessionValidateToolCallRequest))]
[JsonSerializable(typeof(SessionValidateToolCallResponse))]
[JsonSerializable(typeof(SessionMetricsResponse))]
[JsonSerializable(typeof(Dictionary<string, string?>))]
[JsonSerializable(typeof(SessionToolCallResponse))]
[JsonSerializable(typeof(SessionToolCallResponse[]))]
[JsonSerializable(typeof(SessionCheckpointResponse))]
[JsonSerializable(typeof(SessionRollbackRequest))]
[JsonSerializable(typeof(SessionTreeResponse))]
public partial class OpenTailStingrayJsonContext : JsonSerializerContext { }
