using System.Reflection;
using OpenTail.Stingray.Core;
using OpenTail.Stingray.Vulkan;

namespace OpenTail.Stingray.Tests.Vulkan;

/// <summary>
/// Issue #316 — the published NativeAOT binary serves Vulkan shaders from a committed,
/// precompiled SPIR-V table (<see cref="ShadersPrecompiled"/>, generated by tools/SpirvGen)
/// so glslc is never invoked at runtime. These tests are the drift linchpin: they fail if a
/// shader const is added/edited without regenerating the table (scripts/gen-spirv.ps1).
///
/// The completeness/count tests need no GPU. The no-fallback test loads a Vulkan device.
/// </summary>
public sealed unsafe class VulkanPrecompiledShaderTests : HeavyTestBase
{
    /// <summary>
    /// Creates the Vulkan backend, or SKIPS when the device cannot be brought up.
    ///
    /// <para>These tests constructed <c>new VulkanBackend()</c> directly, so an environmental
    /// failure surfaced as a test FAILURE rather than a skip. On this integrated-Radeon machine the
    /// driver intermittently returns <c>ErrorIncompatibleDriver</c> at device creation under
    /// parallel load: one full run showed three such failures while the rest of the class passed,
    /// and a neighbouring guarded test skipped one run and passed the next for the same reason.</para>
    ///
    /// <para>This absorbs failures from the CONSTRUCTOR only. Once a device exists, every shader
    /// assertion runs and fails normally, so the guard cannot hide a correctness defect.
    /// <c>VulkanInitTests</c> is deliberately NOT routed through this — there, bringing the device
    /// up IS the thing under test.</para>
    /// </summary>
    private static global::OpenTail.Stingray.Vulkan.VulkanBackend CreateBackendOrSkip()
    {
        try
        {
            return new global::OpenTail.Stingray.Vulkan.VulkanBackend();
        }
        catch (Exception ex)
        {
            Assert.Skip($"Vulkan device could not be created in this environment: {ex.Message}");
            throw;   // unreachable: Assert.Skip throws
        }
    }

    // SPIR-V magic number 0x07230203, little-endian first four bytes.
    private static readonly byte[] SpirvMagic = { 0x03, 0x02, 0x23, 0x07 };

    // Must stay in lockstep with SpirvGen's own selection rule: `internal` consts are complete
    // shaders that belong in the table, `private` ones are FRAGMENTS concatenated into a shader
    // (e.g. the shared prologue/body behind MatVecBatchedQ4KInt8 and its ...Dp4a variant) and are
    // not independently compilable GLSL. If the two rules ever diverge, this suite reports drift
    // that regeneration cannot fix.
    private static List<(string Name, string Source)> ShaderConsts()
    {
        return typeof(Shaders)
            .GetFields(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static)
            .Where(f => f.IsLiteral && f.FieldType == typeof(string) && !f.IsPrivate)
            .Select(f => (f.Name, (string)f.GetRawConstantValue()!))
            .ToList();
    }

    [Fact]
    public void AllShaderConstantsArePrecompiled()
    {
        var skipped = new HashSet<string>(ShadersPrecompiled.SkippedShaders, StringComparer.Ordinal);
        var consts = ShaderConsts();
        Assert.NotEmpty(consts);

        foreach (var (name, source) in consts)
        {
            ulong hash = ShaderCompiler.StableHash(source);
            bool present = ShadersPrecompiled.TryGet(hash, out var spv);

            if (skipped.Contains(name))
            {
                // Intentionally absent (glslc lacks the required extension); the backend
                // falls back at runtime. It must NOT be in the table.
                Assert.False(present,
                    $"Shader '{name}' is listed in SkippedShaders but is present in the table.");
                continue;
            }

            Assert.True(present,
                $"Shader '{name}' is missing from the precompiled table — regenerate via scripts/gen-spirv.ps1.");
            Assert.True(spv.Length > 0, $"Shader '{name}' has empty SPIR-V.");
            Assert.True(spv.Length >= 4 && spv[0] == SpirvMagic[0] && spv[1] == SpirvMagic[1]
                && spv[2] == SpirvMagic[2] && spv[3] == SpirvMagic[3],
                $"Shader '{name}' does not start with the SPIR-V magic number.");
        }
    }

    [Fact]
    public void PrecompiledTableHasExpectedCount()
    {
        // The precompiled entries plus the intentionally-skipped shaders must account for
        // every Shaders const — catches a partial/stale table (e.g. a new shader not added,
        // or an old one removed but its byte[] left behind).
        int total = ShaderConsts().Count;
        Assert.Equal(total, ShadersPrecompiled.Count + ShadersPrecompiled.SkippedShaders.Length);
    }

    [Fact]
    public void KnownShaderUsesPrecompiledPath_NoGlslcFallback()
    {
        // Construct a Vulkan backend and run an op that builds a pipeline from a shipped
        // shader (RmsNorm). If the precompiled path served it, glslc is never invoked.
        global::OpenTail.Stingray.Vulkan.VulkanBackend backend;
        try { backend = CreateBackendOrSkip(); }
        catch { return; } // no Vulkan device on this host — skip

        using (backend)
        {
            ShaderCompiler.GlslcFallbackCount = 0;

            const int N = 2048;
            var input = new float[N];
            var weight = new float[N];
            var rng = new Random(42);
            for (int i = 0; i < N; i++)
            {
                input[i] = (float)(rng.NextDouble() * 2 - 1);
                weight[i] = (float)(rng.NextDouble() * 0.5 + 0.75);
            }

            var gpuInput = backend.Upload(input, TensorShape.D1(N));
            var gpuWeight = backend.Upload(weight, TensorShape.D1(N));
            var gpuOutput = backend.Allocate(TensorShape.D1(N));
            backend.RmsNorm(gpuOutput, gpuInput, gpuWeight, 1e-5f);

            var gpuResult = new float[N];
            backend.Download(gpuOutput, gpuResult);

            backend.Free(gpuInput);
            backend.Free(gpuWeight);
            backend.Free(gpuOutput);

            Assert.Equal(0, ShaderCompiler.GlslcFallbackCount);
        }
    }
}
